Create DrawGrid.json
GDevelopApp/GDevelop-extensions pull request #1174
Opened 2024-02-18 15:54 UTC by TheGemDev

draw a virtual grid.

<img width="812" alt="image" src="https://github.com/GDevelopApp/GDevelop-extensions/assets/53819287/5e3b89d0-81d5-489c-af93-e638f46b4ebf">

<img width="832" alt="image" src="https://github.com/GDevelopApp/GDevelop-extensions/assets/53819287/d50eba86-c5c8-4c3e-b254-4b38cb9eea00">

<img width="566" alt="image" src="https://github.com/GDevelopApp/GDevelop-extensions/assets/53819287/2cd824cf-b6cf-4cde-a89e-b02efe318d41">

2024-02-18 16:20 UTC, TheGemDev commented
Project - [Draw Grid.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/14323360/Draw.Grid.zip)

Extension - 
[Draw Grid Extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/14323371/DrawGrid.zip)

2024-02-18 16:21 UTC, Oxey405 requested changes
So it's a great idea but there are a few things to fix I think before this gets published
1. Performance
Performance is really bad because of how you draw the cells (using a loop)
At least you should warn people that it's gonna take a long time to render for fine-grain loops
2. Coloring
I think it would also be great to explain how to change the color of the grid for example in the description of the extension, the action or in a help page

Other than that it looks great :)

2024-02-18 16:21 UTC, Oxey405 commented
> Project - [Draw Grid.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/14323360/Draw.Grid.zip)
> 
> Extension - [Draw Grid Extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/14323371/DrawGrid.zip)

Thanks

2024-02-18 18:38 UTC, D8H commented
> Performance is really bad because of how you draw the cells (using a loop)

The issue is not the loop. It's the instance creation.

2024-02-18 19:43 UTC, TheGemDev commented
fixed the performance and added a way to change colors in the action. Also, if no instance of the shape painter object exists,  the action creates one.

<img width="566" alt="image" src="https://github.com/GDevelopApp/GDevelop-extensions/assets/53819287/d0046aeb-d4d8-4491-a59a-ba2bd6598b9a">

2024-03-12 15:56 UTC, D8H commented
What happens when the camera is moved?
Can extension users use the grid to debug path finding of a game with scrolling?
What do you think about making a behavior that updates the grid when needed?

2025-06-30 21:28 UTC, closed without merging