refactor: Improve Promise Handling, Validation, and Code Efficiency Across Scripts
GDevelopApp/GDevelop-extensions pull request #1403
Opened 2024-10-09 14:06 UTC by Viole07

---

### **Pull Request Description :**

Closes #1402

This pull request refactors and improves several scripts in the project by enhancing error handling, improving validation logic, and streamlining promise management. Below are the key changes made across different files:

1. **`verifyExtension.js`:**
   - Refactored promise handling by introducing a `try-catch` block for consistent async error handling across the function.
   - Replaced the mix of `.catch()` and `async/await` with a more streamlined approach, ensuring any unhandled async errors are caught and logged properly.
   - Added detailed error logging to help with debugging during extension verification.

2. **`extract-extension.js`:**
   - Refactored to streamline the promise handling by wrapping the entire function in a `try-catch` block.
   - This ensures that any errors related to loading or extracting the zip file are handled in a single place, providing more consistent error handling.
   - Improved the error logging by including the actual error message in the returned result for better context during debugging.

3. **`ExtensionNameValidator.js`:**
   - Added a type check for `extensionName` to ensure it is a string before proceeding with further validation.
   - This prevents potential runtime errors when invalid data types are passed, making the function more robust.

4. **`PascalCase.js`:**
   - Combined two similar loops into a single loop that processes both `publicEventsFunctions` and `eventsBasedBehaviors`. This reduces code duplication and simplifies the logic.
   - Added a type check for `extension.name` to ensure it is a string before validating the PascalCase, preventing errors when the name is not provided or is of the wrong type.

### **Benefits:**
- Improved code readability and maintainability by consolidating promise handling and reducing redundancy.
- Increased robustness through added type checks and better error logging, making debugging easier.
- Simplified logic by combining redundant loops and refactoring validation functions into smaller, reusable components.

---

2024-10-09 14:34 UTC, Viole07 commented
@4ian , why is this check not passing.. i tried fixing the issue using 

npx prettier --write "scripts/**/*.js" "scripts/**/*.ts"

and it's still not working..

2024-12-15 13:18 UTC, arthuro555 requested changes

2024-12-15 13:18 UTC, arthuro555 commented on scripts/lib/rules/PascalCase.js
> +  }
This offers no new benefit, does an inefficient copy, and unnecessarily complexifies the logic.

2024-12-15 13:18 UTC, arthuro555 commented on scripts/lib/rules/PascalCase.js
> +  }
Typechecking is already statically enforced via typescript: this is unnecessary complexity.

2024-12-15 13:18 UTC, arthuro555 commented on scripts/lib/ExtensionNameValidator.js
> +
Typechecking is already statically enforced via typescript: this is unnecessary complexity.

2024-12-15 13:18 UTC, arthuro555 commented on scripts/extract-extension.js
> +    return { error: 'zip-error', details: e.message };
The try catch block should only cover the block it is handling errors for (the `JSZip.loadAsync` call)

2024-12-15 13:18 UTC, arthuro555 commented on scripts/check-single-extension.js
> +    return { code: 'not-found' }; // Return a default error code, you could also return something more specific based on the context
Most definitely not! The error code determines what error message is sent back to the submitter - sending them a message about a file not being found is not generic, and goes against the point of providing feedback. The script crashing is already a handled case, so this unnecessarily strips the context of the error.

2024-12-15 13:20 UTC, arthuro555 commented
Since every proposed change here does not in fact improve promise handling, validation or code efficiency, I'll close this PR.

2024-12-15 13:20 UTC, closed without merging