Added shape painter option to Multitouch Joystick extension
GDevelopApp/GDevelop-extensions pull request #470
Opened 2022-06-21 01:55 UTC by tristanbob

## Updates

- Added behavior for shape painter (Thanks Melon!)
- Changed wording from "Activate joystick" to "Animate joystick"
- No change to function names to prevent impacting existing games

## Playable game
https://liluo.io/games/968717d9-209e-4a9d-a5e5-f6ec995161cb
Works with touch, mouse, and gamepad inputs (sprite uses controller 1, painter uses controller 2)

## Project files
[MultitouchJoystick Shape Painter.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/8945118/MultitouchJoystick.Shape.Painter.zip)

2022-08-28 01:50 UTC, tristanbob commented
Is anyone interested in approving this change?  Thanks!

2022-08-28 01:56 UTC, tristanbob commented
Hmmmm... how to resolve the conflict?  I think it was caused by moving the extensions into community/reviewed folders.  

1) I could ```Merge branch "Main" into this branch"```

or

2) Close this PR and create a new PR based on current version of "Main"

2022-08-28 10:03 UTC, Bouh commented
- The description don't talk about the shape painter
- 

> Hmmmm... how to resolve the conflict? I think it was caused by moving the extensions into community/reviewed folders.
> 
> 1. I could `Merge branch "Main" into this branch"`
> 
> or
> 
> 2. Close this PR and create a new PR based on current version of "Main"

Like you prefer both works.

Here a short review:
- The description of the extension don't talk about the shape painter and how to use the extension with it.
- `shape painter` can be added in tags.

2022-08-28 10:03 UTC, Bouh requested changes
- The description of the extension don't talk about the shape painter and how to use the extension with it.
- `shape painter` can be added in tags.

2022-09-04 00:21 UTC, tristanbob commented
> * The description of the extension don't talk about the shape painter and how to use the extension with it.

I added this to the description.

> * `shape painter` can be added in tags.

Added.

2022-09-04 00:37 UTC, tristanbob commented
Thanks for the good input, @Bouh!  Here are the updated files, if needed.

## Playable game

https://liluo.io/victrisgames/multitouchjoystick-shape-paint

## Project files

[MultitouchJoystick Shape Painter.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9483599/MultitouchJoystick.Shape.Painter.zip)

2022-10-30 10:00 UTC, tristanbob commented
Reminder to Tristan: check if another PR was created for this.

2023-02-27 22:34 UTC, Bouh commented
Now we have joystick object in the object list.
Is that ok to close this PR?

2023-02-28 07:48 UTC, 4ian commented
I think so yes?

2023-02-28 10:47 UTC, closed without merging