Update PanelSpriteButton.json
GDevelopApp/GDevelop-extensions pull request #980
Opened 2023-08-17 12:02 UTC by gemmomoh

Add disabled state.

A disabled state is visible when the interactions are deactivated.

![image](https://github.com/GDevelopApp/GDevelop-extensions/assets/104901333/6a2f3139-ac03-47ac-ba9c-a4581615bd6f)

2023-08-17 12:20 UTC, D8H commented
Thank you for submitting an extension update.

Did you consider applying an effect on the button after disabling it?

2023-08-17 13:19 UTC, gemmomoh commented
No, I did not add an effect. I think people usually have a disabled button sprite/image.

2023-08-19 12:19 UTC, Bouh commented
As the other states are already in images, it's a good to have this new state as an image too, to be consistent.
The effects are also rendered at each frame, which is a minor hit on the GPU, an additional cost that can be avoided.

2023-08-19 12:48 UTC, Bouh approved these changes

2023-08-19 14:26 UTC, D8H commented
> As the other states are already in images, it's a good to have this new state as an image too, to be consistent. The effects are also rendered at each frame, which is a minor hit on the GPU, an additional cost that can be avoided.

Adding a new state means that every assets from the store must be updated with an image for this state. Also, I think it's not very practical to use an image when, for most buttons, it will just be a grey-ish version of the idle state.

Effects performance is another matter. There is no need to evaluate a shader each frame when the image stays the same.

2023-08-19 14:27 UTC, D8H requested changes
Please, extension team members, do not merge this PR.

2023-08-19 14:48 UTC, 4ian commented
I think we should start thinking about having different variations of buttons :)

2023-08-19 22:20 UTC, Bouh commented
> I think we should start thinking about having different variations of buttons :)

What did you suggest, kept the object in this version, and duplicate the a new object with improvment on a disabled state?
It will duplicate the object buttons just for that difference...

>Also, I think it's not very practical to use an image when, for most buttons, it will just be a grey-ish version of the idle state.

I agree.

>Effects performance is another matter. There is no need to evaluate a shader each frame on a still image.

I think the shaders from effects are calculated at every frame, I'm not sure. But if we can calculate the effect one time on the object its a wonderful solution.
Except the effect doesn't work on children objects in a EBO like I saw and shared on discord, so we can't use them for the moment.

2023-08-24 09:34 UTC, romw314 commented
This PR should have the 'Extension updated' tag

2024-12-16 17:35 UTC, arthuro555 commented
As per the thread above, the reviewers rejected these changes. Closing PR now.

2024-12-16 17:35 UTC, closed without merging